# Generated by Django 4.2.10 on 2024-02-23 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_register_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='file')),
                ('tag', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=100)),
                ('like_count', models.CharField(max_length=100)),
                ('likes', models.CharField(max_length=100)),
                ('registerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.register')),
            ],
        ),
    ]
