# Generated by Django 4.2.10 on 2024-02-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_count',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
